---
- name: "Update /etc/network/interfaces"
  when: ganeti_net is defined
  template:
    dest: /etc/network/interfaces
    backup: yes
    force: yes
    src: interfaces.j2

# FIXME: not just first interface
- name: "Create forward zonefiles"
  when: ganeti_net is defined and ganeti_net[0].ipv4 is defined
  local_action:
    module: template
    src: zonefile-forward.j2
    dest: "/etc/bind/db.{{ ansible_domain }}"
    validate: "named-checkzone {{ansible_domain}} %s"
    force: no
  notify: reload local bind9

# FIXME: not just first interface
- name: "remove old dns entries from forward lookup zonefile (FQ)"
  when: ganeti_net is defined and ganeti_net[0].ipv4 is defined
  local_action:
    module: lineinfile
    dest: "/etc/bind/db.{{ ansible_domain }}"
    regexp: "^{{ ansible_fqdn }}.[ \t0-9]+IN[ \t]+A[ \t]+(?!{{ganeti_net|map(attribute='ipv4')|join('\n|')}}\n)"
    state: absent
    validate: "named-checkzone {{ansible_domain}} %s"
  notify: reload local bind9

# FIXME: not just first interface
- name: "remove old dns entries from forward lookup zonefile (host)"
  when: ganeti_net is defined and ganeti_net[0].ipv4 is defined
  local_action:
    module: lineinfile
    dest: "/etc/bind/db.{{ ansible_domain }}"
    regexp: "^{{ ansible_hostname }}[ \t0-9]+IN[ \t]+A[ \t]+(?!{{ganeti_net|map(attribute='ipv4')|join('\n|')}}\n)"
    state: absent
    validate: "named-checkzone {{ansible_domain}} %s"
  notify: reload local bind9

- name: "Add forward lookup to hostname"
  when: ganeti_net is defined and item.ipv4 is defined
  local_action:
    module: lineinfile
    dest: "/etc/bind/db.{{ ansible_domain }}"
    line: "{{ansible_hostname}}	18000	IN	A	{{ item.ipv4 }}"
    validate: "named-checkzone {{ansible_domain}} %s"
  with_items: ganeti_net
  notify: reload local bind9

- name: "Create reverse zonefiles"
  when: ganeti_net is defined and item.nw is defined
  local_action:
    module: template
    src: zonefile-reverse.j2
    dest: "/etc/bind/db.{{ item.nw | revzone }}"
    force: no
  with_items: ganeti_net
  notify: reload local bind9

- name: "Add reverse lookup to hostname"
  when: ganeti_net is defined and item.nw is defined
  local_action:
    module: lineinfile
    dest: /etc/bind/db.{{item.nw | revzone }}
    regexp: "^{{item.ipv4 | ipaddr('revdns') }}"
    line: "{{item.ipv4 | ipaddr('revdns') }}	18000	IN	PTR	{{ ansible_fqdn }}."
  with_items: ganeti_net
  notify: reload local bind9


- name: "flush handlers"
  meta: flush_handlers

# vim:ff=unix ts=2 sw=2 ai expandtab
